-- Database Schema Migration for Headshots Application
-- This migration recreates the complete database schema including tables, constraints, RLS policies, and permissions

-- Set up basic session parameters
SET client_min_messages = warning;

-- Create required extensions (only the essential ones for this schema)
-- Note: Some extensions may already be enabled in Supabase or may not be needed
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Set default table access method
SET default_tablespace = '';
SET default_table_access_method = "heap";

-- =====================================================
-- TABLE DEFINITIONS
-- =====================================================

-- Credits table: Tracks user credit balances for service usage
CREATE TABLE IF NOT EXISTS "public"."credits" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "credits" integer DEFAULT 0 NOT NULL,
    "user_id" "uuid" NOT NULL
);

ALTER TABLE "public"."credits" OWNER TO "postgres";

-- Set up auto-incrementing ID for credits table
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_sequences WHERE sequencename = 'credits_id_seq' AND schemaname = 'public') THEN
        ALTER TABLE "public"."credits" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
            SEQUENCE NAME "public"."credits_id_seq"
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );
    END IF;
END $$;

-- Models table: Stores information about user-trained AI models
CREATE TABLE IF NOT EXISTS "public"."models" (
    "id" bigint NOT NULL,
    "name" "text",
    "type" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid",
    "status" "text" DEFAULT 'processing'::"text" NOT NULL,
    "modelId" "text"
);

ALTER TABLE "public"."models" OWNER TO "postgres";

-- Set up auto-incrementing ID for models table
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_sequences WHERE sequencename = 'models_id_seq' AND schemaname = 'public') THEN
        ALTER TABLE "public"."models" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
            SEQUENCE NAME "public"."models_id_seq"
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );
    END IF;
END $$;

-- Samples table: Contains training images uploaded by users
CREATE TABLE IF NOT EXISTS "public"."samples" (
    "id" bigint NOT NULL,
    "uri" "text" NOT NULL,
    "modelId" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."samples" OWNER TO "postgres";

-- Set up auto-incrementing ID for samples table
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_sequences WHERE sequencename = 'samples_id_seq' AND schemaname = 'public') THEN
        ALTER TABLE "public"."samples" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
            SEQUENCE NAME "public"."samples_id_seq"
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );
    END IF;
END $$;

-- Images table: Stores generated headshot results
CREATE TABLE IF NOT EXISTS "public"."images" (
    "id" bigint NOT NULL,
    "modelId" bigint NOT NULL,
    "uri" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."images" OWNER TO "postgres";

-- Set up auto-incrementing ID for images table
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_sequences WHERE sequencename = 'images_id_seq' AND schemaname = 'public') THEN
        ALTER TABLE "public"."images" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
            SEQUENCE NAME "public"."images_id_seq"
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );
    END IF;
END $$;

-- =====================================================
-- PRIMARY KEY CONSTRAINTS (CONDITIONAL)
-- =====================================================

-- Add primary key constraints only if they don't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'credits_pkey') THEN
        ALTER TABLE ONLY "public"."credits" ADD CONSTRAINT "credits_pkey" PRIMARY KEY ("id");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'models_pkey') THEN
        ALTER TABLE ONLY "public"."models" ADD CONSTRAINT "models_pkey" PRIMARY KEY ("id");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'samples_pkey') THEN
        ALTER TABLE ONLY "public"."samples" ADD CONSTRAINT "samples_pkey" PRIMARY KEY ("id");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'images_pkey') THEN
        ALTER TABLE ONLY "public"."images" ADD CONSTRAINT "images_pkey" PRIMARY KEY ("id");
    END IF;
END $$;

-- =====================================================
-- FOREIGN KEY CONSTRAINTS (CONDITIONAL)
-- =====================================================

-- Add foreign key constraints only if they don't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'credits_user_id_fkey') THEN
        ALTER TABLE ONLY "public"."credits" ADD CONSTRAINT "credits_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'models_user_id_fkey') THEN
        ALTER TABLE ONLY "public"."models" ADD CONSTRAINT "models_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'samples_modelId_fkey') THEN
        ALTER TABLE ONLY "public"."samples" ADD CONSTRAINT "samples_modelId_fkey" FOREIGN KEY ("modelId") REFERENCES "public"."models"("id") ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'images_modelId_fkey') THEN
        ALTER TABLE ONLY "public"."images" ADD CONSTRAINT "images_modelId_fkey" FOREIGN KEY ("modelId") REFERENCES "public"."models"("id") ON DELETE CASCADE;
    END IF;
END $$;

-- =====================================================
-- ROW LEVEL SECURITY POLICIES
-- =====================================================

-- Enable RLS on all tables first
ALTER TABLE "public"."credits" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."models" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."samples" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."images" ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist to avoid conflicts
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON "public"."credits";
DROP POLICY IF EXISTS "Enable insert for service role" ON "public"."credits";
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON "public"."credits";
DROP POLICY IF EXISTS "Enable read access for service role" ON "public"."credits";
DROP POLICY IF EXISTS "Enable update for authenticated users" ON "public"."credits";
DROP POLICY IF EXISTS "Enable update for service role" ON "public"."credits";

DROP POLICY IF EXISTS "Enable insert for signed in users" ON "public"."models";
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON "public"."models";
DROP POLICY IF EXISTS "Enable update for authenticated users" ON "public"."models";
DROP POLICY IF EXISTS "Enable update from service role" ON "public"."models";
DROP POLICY IF EXISTS "Enable delete for authenticated users" ON "public"."models";

DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON "public"."samples";
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON "public"."samples";
DROP POLICY IF EXISTS "Enable updates for authenticated users to samples" ON "public"."samples";
DROP POLICY IF EXISTS "Enable delete for authenticated users" ON "public"."samples";

DROP POLICY IF EXISTS "Enable insert for authenticated users" ON "public"."images";
DROP POLICY IF EXISTS "Enable insert for service role" ON "public"."images";
DROP POLICY IF EXISTS "Enable read access for all authenticated users" ON "public"."images";
DROP POLICY IF EXISTS "Enable update for authenticated users" ON "public"."images";
DROP POLICY IF EXISTS "Enable delete for authenticated users" ON "public"."images";

-- Credits table policies
CREATE POLICY "Enable insert for authenticated users only" ON "public"."credits" FOR INSERT TO "authenticated" WITH CHECK (((SELECT "auth"."uid"()) = "user_id"));

CREATE POLICY "Enable insert for service role" ON "public"."credits" FOR INSERT TO "service_role" WITH CHECK (true);

CREATE POLICY "Enable read access for authenticated users" ON "public"."credits" FOR SELECT TO "authenticated" USING (((SELECT "auth"."uid"()) = "user_id"));

CREATE POLICY "Enable read access for service role" ON "public"."credits" FOR SELECT TO "service_role" USING (true);

CREATE POLICY "Enable update for authenticated users" ON "public"."credits" FOR UPDATE TO "authenticated" USING (((SELECT "auth"."uid"()) = "user_id")) WITH CHECK (((SELECT "auth"."uid"()) = "user_id"));

CREATE POLICY "Enable update for service role" ON "public"."credits" FOR UPDATE TO "service_role" USING (true) WITH CHECK (true);

-- Models table policies
CREATE POLICY "Enable insert for signed in users" ON "public"."models" FOR INSERT TO "authenticated" WITH CHECK (("user_id" = (SELECT "auth"."uid"())));

CREATE POLICY "Enable read access for authenticated users" ON "public"."models" FOR SELECT TO "authenticated" USING (((SELECT "auth"."uid"()) = "user_id"));

CREATE POLICY "Enable update for authenticated users" ON "public"."models" FOR UPDATE TO "authenticated" USING (((SELECT "auth"."uid"()) = "user_id")) WITH CHECK (((SELECT "auth"."uid"()) = "user_id"));

CREATE POLICY "Enable update from service role" ON "public"."models" FOR UPDATE TO "service_role" USING (true) WITH CHECK (true);

CREATE POLICY "Enable delete for authenticated users" ON "public"."models" FOR DELETE TO "authenticated" USING (((SELECT "auth"."uid"()) = "user_id"));

-- Samples table policies
CREATE POLICY "Enable insert for authenticated users only" ON "public"."samples" FOR INSERT TO "authenticated" WITH CHECK (((SELECT "auth"."uid"()) = ( SELECT "models"."user_id"
   FROM "public"."models"
  WHERE ("models"."id" = "samples"."modelId"))));

CREATE POLICY "Enable read access for authenticated users" ON "public"."samples" FOR SELECT TO "authenticated" USING (((SELECT "auth"."uid"()) = ( SELECT "models"."user_id"
   FROM "public"."models"
  WHERE ("models"."id" = "samples"."modelId"))));

CREATE POLICY "Enable updates for authenticated users to samples" ON "public"."samples" FOR UPDATE TO "authenticated" USING (((SELECT "auth"."uid"()) = ( SELECT "models"."user_id"
   FROM "public"."models"
  WHERE ("models"."id" = "samples"."modelId")))) WITH CHECK (((SELECT "auth"."uid"()) = ( SELECT "models"."user_id"
   FROM "public"."models"
  WHERE ("models"."id" = "samples"."modelId"))));

CREATE POLICY "Enable delete for authenticated users" ON "public"."samples" FOR DELETE TO "authenticated" USING (((SELECT "auth"."uid"()) = ( SELECT "models"."user_id"
   FROM "public"."models"
  WHERE ("models"."id" = "samples"."modelId"))));

-- Images table policies
CREATE POLICY "Enable insert for authenticated users" ON "public"."images" FOR INSERT TO "authenticated" WITH CHECK (((SELECT "auth"."uid"()) = ( SELECT "models"."user_id"
   FROM "public"."models"
  WHERE ("models"."id" = "images"."modelId"))));

CREATE POLICY "Enable insert for service role" ON "public"."images" FOR INSERT TO "service_role" WITH CHECK (true);

CREATE POLICY "Enable read access for all authenticated users" ON "public"."images" FOR SELECT TO "authenticated" USING (((SELECT "auth"."uid"()) = ( SELECT "models"."user_id"
   FROM "public"."models"
  WHERE ("models"."id" = "images"."modelId"))));

CREATE POLICY "Enable update for authenticated users" ON "public"."images" FOR UPDATE TO "authenticated" USING (((SELECT "auth"."uid"()) = ( SELECT "models"."user_id"
   FROM "public"."models"
  WHERE ("models"."id" = "images"."modelId")))) WITH CHECK (((SELECT "auth"."uid"()) = ( SELECT "models"."user_id"
   FROM "public"."models"
  WHERE ("models"."id" = "images"."modelId"))));

CREATE POLICY "Enable delete for authenticated users" ON "public"."images" FOR DELETE TO "authenticated" USING (((SELECT "auth"."uid"()) = ( SELECT "models"."user_id"
   FROM "public"."models"
  WHERE ("models"."id" = "images"."modelId"))));

-- =====================================================
-- SCHEMA PERMISSIONS
-- =====================================================

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

-- =====================================================
-- TABLE PERMISSIONS
-- =====================================================

-- Credits table permissions
GRANT ALL ON TABLE "public"."credits" TO "anon";
GRANT ALL ON TABLE "public"."credits" TO "authenticated";
GRANT ALL ON TABLE "public"."credits" TO "service_role";

-- Models table permissions
GRANT ALL ON TABLE "public"."models" TO "anon";
GRANT ALL ON TABLE "public"."models" TO "authenticated";
GRANT ALL ON TABLE "public"."models" TO "service_role";

-- Samples table permissions
GRANT ALL ON TABLE "public"."samples" TO "anon";
GRANT ALL ON TABLE "public"."samples" TO "authenticated";
GRANT ALL ON TABLE "public"."samples" TO "service_role";

-- Images table permissions
GRANT ALL ON TABLE "public"."images" TO "anon";
GRANT ALL ON TABLE "public"."images" TO "authenticated";
GRANT ALL ON TABLE "public"."images" TO "service_role";

-- Sequence permissions (conditional)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_sequences WHERE sequencename = 'credits_id_seq' AND schemaname = 'public') THEN
        GRANT ALL ON SEQUENCE "public"."credits_id_seq" TO "anon";
        GRANT ALL ON SEQUENCE "public"."credits_id_seq" TO "authenticated";
        GRANT ALL ON SEQUENCE "public"."credits_id_seq" TO "service_role";
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_sequences WHERE sequencename = 'models_id_seq' AND schemaname = 'public') THEN
        GRANT ALL ON SEQUENCE "public"."models_id_seq" TO "anon";
        GRANT ALL ON SEQUENCE "public"."models_id_seq" TO "authenticated";
        GRANT ALL ON SEQUENCE "public"."models_id_seq" TO "service_role";
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_sequences WHERE sequencename = 'samples_id_seq' AND schemaname = 'public') THEN
        GRANT ALL ON SEQUENCE "public"."samples_id_seq" TO "anon";
        GRANT ALL ON SEQUENCE "public"."samples_id_seq" TO "authenticated";
        GRANT ALL ON SEQUENCE "public"."samples_id_seq" TO "service_role";
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_sequences WHERE sequencename = 'images_id_seq' AND schemaname = 'public') THEN
        GRANT ALL ON SEQUENCE "public"."images_id_seq" TO "anon";
        GRANT ALL ON SEQUENCE "public"."images_id_seq" TO "authenticated";
        GRANT ALL ON SEQUENCE "public"."images_id_seq" TO "service_role";
    END IF;
END $$;

-- =====================================================
-- DEFAULT PRIVILEGES
-- =====================================================

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";

-- Migration complete
-- Note: For production use, apply the secure permissions migration (20250915000001_secure_permissions.sql)
-- which implements proper role-based permissions following the principle of least privilege