-- Cost Tracking Migration
-- Adds tables for tracking training costs, estimates, and budget alerts

-- Training costs table: Tracks actual costs for completed training jobs
CREATE TABLE IF NOT EXISTS "public"."training_costs" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "model_id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "training_id" "text" NOT NULL,
    "service_provider" "text" NOT NULL DEFAULT 'runpod',
    "gpu_type" "text",
    "training_start_time" timestamp with time zone,
    "training_end_time" timestamp with time zone,
    "training_duration_minutes" integer,
    "gpu_cost_per_hour" decimal(10,4),
    "total_cost" decimal(10,4) NOT NULL,
    "currency" "text" DEFAULT 'USD' NOT NULL,
    "cost_breakdown" jsonb,
    "training_parameters" jsonb,
    "status" "text" DEFAULT 'completed' NOT NULL
);

ALTER TABLE "public"."training_costs" OWNER TO "postgres";

-- Set up auto-incrementing ID for training_costs table
ALTER TABLE "public"."training_costs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."training_costs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Cost estimates table: Stores cost predictions before training starts
CREATE TABLE IF NOT EXISTS "public"."cost_estimates" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "service_provider" "text" NOT NULL DEFAULT 'runpod',
    "image_count" integer NOT NULL,
    "estimated_training_time_minutes" integer,
    "estimated_cost" decimal(10,4) NOT NULL,
    "currency" "text" DEFAULT 'USD' NOT NULL,
    "cost_breakdown" jsonb,
    "training_parameters" jsonb,
    "actual_training_id" "text",
    "actual_cost_id" bigint
);

ALTER TABLE "public"."cost_estimates" OWNER TO "postgres";

-- Set up auto-incrementing ID for cost_estimates table
ALTER TABLE "public"."cost_estimates" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."cost_estimates_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Budget alerts table: Tracks budget thresholds and alerts
CREATE TABLE IF NOT EXISTS "public"."budget_alerts" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "alert_type" "text" NOT NULL, -- 'daily', 'weekly', 'monthly', 'per_training'
    "threshold_amount" decimal(10,4) NOT NULL,
    "currency" "text" DEFAULT 'USD' NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "last_triggered" timestamp with time zone,
    "notification_email" "text",
    "notification_webhook" "text"
);

ALTER TABLE "public"."budget_alerts" OWNER TO "postgres";

-- Set up auto-incrementing ID for budget_alerts table
ALTER TABLE "public"."budget_alerts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."budget_alerts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Budget alert notifications table: Tracks when alerts are triggered
CREATE TABLE IF NOT EXISTS "public"."budget_alert_notifications" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "budget_alert_id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "triggered_amount" decimal(10,4) NOT NULL,
    "period_start" timestamp with time zone,
    "period_end" timestamp with time zone,
    "notification_sent" boolean DEFAULT false NOT NULL,
    "notification_method" "text", -- 'email', 'webhook', 'both'
    "notification_details" jsonb
);

ALTER TABLE "public"."budget_alert_notifications" OWNER TO "postgres";

-- Set up auto-incrementing ID for budget_alert_notifications table
ALTER TABLE "public"."budget_alert_notifications" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."budget_alert_notifications_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Add primary key constraints
ALTER TABLE ONLY "public"."training_costs" ADD CONSTRAINT "training_costs_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."cost_estimates" ADD CONSTRAINT "cost_estimates_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."budget_alerts" ADD CONSTRAINT "budget_alerts_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."budget_alert_notifications" ADD CONSTRAINT "budget_alert_notifications_pkey" PRIMARY KEY ("id");

-- Add foreign key constraints
ALTER TABLE ONLY "public"."training_costs" ADD CONSTRAINT "training_costs_model_id_fkey" FOREIGN KEY ("model_id") REFERENCES "public"."models"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."training_costs" ADD CONSTRAINT "training_costs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."cost_estimates" ADD CONSTRAINT "cost_estimates_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."cost_estimates" ADD CONSTRAINT "cost_estimates_actual_cost_id_fkey" FOREIGN KEY ("actual_cost_id") REFERENCES "public"."training_costs"("id") ON DELETE SET NULL;
ALTER TABLE ONLY "public"."budget_alerts" ADD CONSTRAINT "budget_alerts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."budget_alert_notifications" ADD CONSTRAINT "budget_alert_notifications_budget_alert_id_fkey" FOREIGN KEY ("budget_alert_id") REFERENCES "public"."budget_alerts"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."budget_alert_notifications" ADD CONSTRAINT "budget_alert_notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

-- Add indexes for better query performance
CREATE INDEX IF NOT EXISTS "training_costs_user_id_idx" ON "public"."training_costs" ("user_id");
CREATE INDEX IF NOT EXISTS "training_costs_model_id_idx" ON "public"."training_costs" ("model_id");
CREATE INDEX IF NOT EXISTS "training_costs_training_id_idx" ON "public"."training_costs" ("training_id");
CREATE INDEX IF NOT EXISTS "training_costs_created_at_idx" ON "public"."training_costs" ("created_at");
CREATE INDEX IF NOT EXISTS "cost_estimates_user_id_idx" ON "public"."cost_estimates" ("user_id");
CREATE INDEX IF NOT EXISTS "cost_estimates_created_at_idx" ON "public"."cost_estimates" ("created_at");
CREATE INDEX IF NOT EXISTS "budget_alerts_user_id_idx" ON "public"."budget_alerts" ("user_id");
CREATE INDEX IF NOT EXISTS "budget_alert_notifications_user_id_idx" ON "public"."budget_alert_notifications" ("user_id");
CREATE INDEX IF NOT EXISTS "budget_alert_notifications_created_at_idx" ON "public"."budget_alert_notifications" ("created_at");

-- Enable RLS on all new tables
ALTER TABLE "public"."training_costs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."cost_estimates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."budget_alerts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."budget_alert_notifications" ENABLE ROW LEVEL SECURITY;

-- RLS policies for training_costs
CREATE POLICY "Enable read access for authenticated users" ON "public"."training_costs" FOR SELECT TO "authenticated" USING (((SELECT "auth"."uid"()) = "user_id"));
CREATE POLICY "Enable insert for service role" ON "public"."training_costs" FOR INSERT TO "service_role" WITH CHECK (true);
CREATE POLICY "Enable update for service role" ON "public"."training_costs" FOR UPDATE TO "service_role" USING (true) WITH CHECK (true);

-- RLS policies for cost_estimates
CREATE POLICY "Enable read access for authenticated users" ON "public"."cost_estimates" FOR SELECT TO "authenticated" USING (((SELECT "auth"."uid"()) = "user_id"));
CREATE POLICY "Enable insert for authenticated users" ON "public"."cost_estimates" FOR INSERT TO "authenticated" WITH CHECK (((SELECT "auth"."uid"()) = "user_id"));
CREATE POLICY "Enable insert for service role" ON "public"."cost_estimates" FOR INSERT TO "service_role" WITH CHECK (true);
CREATE POLICY "Enable update for service role" ON "public"."cost_estimates" FOR UPDATE TO "service_role" USING (true) WITH CHECK (true);

-- RLS policies for budget_alerts
CREATE POLICY "Enable all access for authenticated users" ON "public"."budget_alerts" FOR ALL TO "authenticated" USING (((SELECT "auth"."uid"()) = "user_id")) WITH CHECK (((SELECT "auth"."uid"()) = "user_id"));
CREATE POLICY "Enable read access for service role" ON "public"."budget_alerts" FOR SELECT TO "service_role" USING (true);

-- RLS policies for budget_alert_notifications
CREATE POLICY "Enable read access for authenticated users" ON "public"."budget_alert_notifications" FOR SELECT TO "authenticated" USING (((SELECT "auth"."uid"()) = "user_id"));
CREATE POLICY "Enable insert for service role" ON "public"."budget_alert_notifications" FOR INSERT TO "service_role" WITH CHECK (true);
CREATE POLICY "Enable update for service role" ON "public"."budget_alert_notifications" FOR UPDATE TO "service_role" USING (true) WITH CHECK (true);

-- Grant permissions
GRANT ALL ON TABLE "public"."training_costs" TO "anon";
GRANT ALL ON TABLE "public"."training_costs" TO "authenticated";
GRANT ALL ON TABLE "public"."training_costs" TO "service_role";

GRANT ALL ON TABLE "public"."cost_estimates" TO "anon";
GRANT ALL ON TABLE "public"."cost_estimates" TO "authenticated";
GRANT ALL ON TABLE "public"."cost_estimates" TO "service_role";

GRANT ALL ON TABLE "public"."budget_alerts" TO "anon";
GRANT ALL ON TABLE "public"."budget_alerts" TO "authenticated";
GRANT ALL ON TABLE "public"."budget_alerts" TO "service_role";

GRANT ALL ON TABLE "public"."budget_alert_notifications" TO "anon";
GRANT ALL ON TABLE "public"."budget_alert_notifications" TO "authenticated";
GRANT ALL ON TABLE "public"."budget_alert_notifications" TO "service_role";

-- Grant sequence permissions
GRANT ALL ON SEQUENCE "public"."training_costs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."training_costs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."training_costs_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."cost_estimates_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."cost_estimates_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."cost_estimates_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."budget_alerts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."budget_alerts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."budget_alerts_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."budget_alert_notifications_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."budget_alert_notifications_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."budget_alert_notifications_id_seq" TO "service_role";

-- Add trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_training_costs_updated_at BEFORE UPDATE ON "public"."training_costs" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_budget_alerts_updated_at BEFORE UPDATE ON "public"."budget_alerts" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();